"""Constants for the OEFR Energy integration."""

DOMAIN = "octopus_french"

CONF_ACCOUNT_NUMBER = "account_number"

LEDGER_TYPE_ELECTRICITY = "FRA_ELECTRICITY_LEDGER"
LEDGER_TYPE_GAS = "FRA_GAS_LEDGER"
LEDGER_TYPE_POT = "POT_LEDGER"

DEFAULT_SCAN_INTERVAL = 60
PREVIOUS_MONTH_OVERLAP_DAYS = 7

SERVICE_FORCE_UPDATE = "force_update"

TARIFF_TYPE_TEMPO = "TEMPO"

TEMPO_STATISTICS_LABELS: frozenset[str] = frozenset({
    "CONSUMPTION_OCTOFLEX_4_V4_HPE_0.0_37.0",
    "CONSUMPTION_OCTOFLEX_4_V4_HCE_0.0_37.0",
    "CONSUMPTION_OCTOFLEX_4_V4_HPHI_0.0_37.0",
    "CONSUMPTION_OCTOFLEX_4_V4_HCHI_0.0_37.0",
    "CONSUMPTION_OCTOFLEX_4_V4_HPP_0.0_37.0",
    "CONSUMPTION_OCTOFLEX_4_V4_HCP_0.0_37.0",
})

TEMPO_PRODUCT_CODE_KEYWORDS: tuple[str, ...] = ("TEMPO", "OCTOFLEX")

TEMPO_CALENDAR_COLORS: frozenset[str] = frozenset({"ETE", "HIVER", "ROUGE"})
