name: "Validate with HACS"

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:

  hacs: # https://github.com/hacs/action
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v5.0.0"
          with:
            category: "integration"
